/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TenantImport } from './routes/tenant'
import { Route as SettingImport } from './routes/setting'
import { Route as ProfileImport } from './routes/profile'
import { Route as HomepageImport } from './routes/homepage'
import { Route as UnauthIndexImport } from './routes/_unauth/index'
import { Route as UnauthRegisterImport } from './routes/_unauth/register'
import { Route as UnauthLandingpageImport } from './routes/_unauth/landingpage'
import { Route as UnauthForgotPasswordImport } from './routes/_unauth/forgotPassword'
import { Route as TenantUserUserManagementImport } from './routes/tenant/user/user-management'
import { Route as TenantPenjualanSalesInvoiceImport } from './routes/tenant/penjualan/sales-invoice'
import { Route as TenantPenjualanChasierImport } from './routes/tenant/penjualan/chasier'
import { Route as TenantMasterDataProductsImport } from './routes/tenant/master-data/products'

// Create/Update Routes

const TenantRoute = TenantImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRoute,
} as any)

const SettingRoute = SettingImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const HomepageRoute = HomepageImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => rootRoute,
} as any)

const UnauthIndexRoute = UnauthIndexImport.update({
  id: '/_unauth/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UnauthRegisterRoute = UnauthRegisterImport.update({
  id: '/_unauth/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const UnauthLandingpageRoute = UnauthLandingpageImport.update({
  id: '/_unauth/landingpage',
  path: '/landingpage',
  getParentRoute: () => rootRoute,
} as any)

const UnauthForgotPasswordRoute = UnauthForgotPasswordImport.update({
  id: '/_unauth/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => rootRoute,
} as any)

const TenantUserUserManagementRoute = TenantUserUserManagementImport.update({
  id: '/user/user-management',
  path: '/user/user-management',
  getParentRoute: () => TenantRoute,
} as any)

const TenantPenjualanSalesInvoiceRoute =
  TenantPenjualanSalesInvoiceImport.update({
    id: '/penjualan/sales-invoice',
    path: '/penjualan/sales-invoice',
    getParentRoute: () => TenantRoute,
  } as any)

const TenantPenjualanChasierRoute = TenantPenjualanChasierImport.update({
  id: '/penjualan/chasier',
  path: '/penjualan/chasier',
  getParentRoute: () => TenantRoute,
} as any)

const TenantMasterDataProductsRoute = TenantMasterDataProductsImport.update({
  id: '/master-data/products',
  path: '/master-data/products',
  getParentRoute: () => TenantRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/homepage': {
      id: '/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof HomepageImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingImport
      parentRoute: typeof rootRoute
    }
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantImport
      parentRoute: typeof rootRoute
    }
    '/_unauth/forgotPassword': {
      id: '/_unauth/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof UnauthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_unauth/landingpage': {
      id: '/_unauth/landingpage'
      path: '/landingpage'
      fullPath: '/landingpage'
      preLoaderRoute: typeof UnauthLandingpageImport
      parentRoute: typeof rootRoute
    }
    '/_unauth/register': {
      id: '/_unauth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof UnauthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/_unauth/': {
      id: '/_unauth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UnauthIndexImport
      parentRoute: typeof rootRoute
    }
    '/tenant/master-data/products': {
      id: '/tenant/master-data/products'
      path: '/master-data/products'
      fullPath: '/tenant/master-data/products'
      preLoaderRoute: typeof TenantMasterDataProductsImport
      parentRoute: typeof TenantImport
    }
    '/tenant/penjualan/chasier': {
      id: '/tenant/penjualan/chasier'
      path: '/penjualan/chasier'
      fullPath: '/tenant/penjualan/chasier'
      preLoaderRoute: typeof TenantPenjualanChasierImport
      parentRoute: typeof TenantImport
    }
    '/tenant/penjualan/sales-invoice': {
      id: '/tenant/penjualan/sales-invoice'
      path: '/penjualan/sales-invoice'
      fullPath: '/tenant/penjualan/sales-invoice'
      preLoaderRoute: typeof TenantPenjualanSalesInvoiceImport
      parentRoute: typeof TenantImport
    }
    '/tenant/user/user-management': {
      id: '/tenant/user/user-management'
      path: '/user/user-management'
      fullPath: '/tenant/user/user-management'
      preLoaderRoute: typeof TenantUserUserManagementImport
      parentRoute: typeof TenantImport
    }
  }
}

// Create and export the route tree

interface TenantRouteChildren {
  TenantMasterDataProductsRoute: typeof TenantMasterDataProductsRoute
  TenantPenjualanChasierRoute: typeof TenantPenjualanChasierRoute
  TenantPenjualanSalesInvoiceRoute: typeof TenantPenjualanSalesInvoiceRoute
  TenantUserUserManagementRoute: typeof TenantUserUserManagementRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantMasterDataProductsRoute: TenantMasterDataProductsRoute,
  TenantPenjualanChasierRoute: TenantPenjualanChasierRoute,
  TenantPenjualanSalesInvoiceRoute: TenantPenjualanSalesInvoiceRoute,
  TenantUserUserManagementRoute: TenantUserUserManagementRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

export interface FileRoutesByFullPath {
  '/homepage': typeof HomepageRoute
  '/profile': typeof ProfileRoute
  '/setting': typeof SettingRoute
  '/tenant': typeof TenantRouteWithChildren
  '/forgotPassword': typeof UnauthForgotPasswordRoute
  '/landingpage': typeof UnauthLandingpageRoute
  '/register': typeof UnauthRegisterRoute
  '/': typeof UnauthIndexRoute
  '/tenant/master-data/products': typeof TenantMasterDataProductsRoute
  '/tenant/penjualan/chasier': typeof TenantPenjualanChasierRoute
  '/tenant/penjualan/sales-invoice': typeof TenantPenjualanSalesInvoiceRoute
  '/tenant/user/user-management': typeof TenantUserUserManagementRoute
}

export interface FileRoutesByTo {
  '/homepage': typeof HomepageRoute
  '/profile': typeof ProfileRoute
  '/setting': typeof SettingRoute
  '/tenant': typeof TenantRouteWithChildren
  '/forgotPassword': typeof UnauthForgotPasswordRoute
  '/landingpage': typeof UnauthLandingpageRoute
  '/register': typeof UnauthRegisterRoute
  '/': typeof UnauthIndexRoute
  '/tenant/master-data/products': typeof TenantMasterDataProductsRoute
  '/tenant/penjualan/chasier': typeof TenantPenjualanChasierRoute
  '/tenant/penjualan/sales-invoice': typeof TenantPenjualanSalesInvoiceRoute
  '/tenant/user/user-management': typeof TenantUserUserManagementRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/homepage': typeof HomepageRoute
  '/profile': typeof ProfileRoute
  '/setting': typeof SettingRoute
  '/tenant': typeof TenantRouteWithChildren
  '/_unauth/forgotPassword': typeof UnauthForgotPasswordRoute
  '/_unauth/landingpage': typeof UnauthLandingpageRoute
  '/_unauth/register': typeof UnauthRegisterRoute
  '/_unauth/': typeof UnauthIndexRoute
  '/tenant/master-data/products': typeof TenantMasterDataProductsRoute
  '/tenant/penjualan/chasier': typeof TenantPenjualanChasierRoute
  '/tenant/penjualan/sales-invoice': typeof TenantPenjualanSalesInvoiceRoute
  '/tenant/user/user-management': typeof TenantUserUserManagementRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/homepage'
    | '/profile'
    | '/setting'
    | '/tenant'
    | '/forgotPassword'
    | '/landingpage'
    | '/register'
    | '/'
    | '/tenant/master-data/products'
    | '/tenant/penjualan/chasier'
    | '/tenant/penjualan/sales-invoice'
    | '/tenant/user/user-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/homepage'
    | '/profile'
    | '/setting'
    | '/tenant'
    | '/forgotPassword'
    | '/landingpage'
    | '/register'
    | '/'
    | '/tenant/master-data/products'
    | '/tenant/penjualan/chasier'
    | '/tenant/penjualan/sales-invoice'
    | '/tenant/user/user-management'
  id:
    | '__root__'
    | '/homepage'
    | '/profile'
    | '/setting'
    | '/tenant'
    | '/_unauth/forgotPassword'
    | '/_unauth/landingpage'
    | '/_unauth/register'
    | '/_unauth/'
    | '/tenant/master-data/products'
    | '/tenant/penjualan/chasier'
    | '/tenant/penjualan/sales-invoice'
    | '/tenant/user/user-management'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomepageRoute: typeof HomepageRoute
  ProfileRoute: typeof ProfileRoute
  SettingRoute: typeof SettingRoute
  TenantRoute: typeof TenantRouteWithChildren
  UnauthForgotPasswordRoute: typeof UnauthForgotPasswordRoute
  UnauthLandingpageRoute: typeof UnauthLandingpageRoute
  UnauthRegisterRoute: typeof UnauthRegisterRoute
  UnauthIndexRoute: typeof UnauthIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomepageRoute: HomepageRoute,
  ProfileRoute: ProfileRoute,
  SettingRoute: SettingRoute,
  TenantRoute: TenantRouteWithChildren,
  UnauthForgotPasswordRoute: UnauthForgotPasswordRoute,
  UnauthLandingpageRoute: UnauthLandingpageRoute,
  UnauthRegisterRoute: UnauthRegisterRoute,
  UnauthIndexRoute: UnauthIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/homepage",
        "/profile",
        "/setting",
        "/tenant",
        "/_unauth/forgotPassword",
        "/_unauth/landingpage",
        "/_unauth/register",
        "/_unauth/"
      ]
    },
    "/homepage": {
      "filePath": "homepage.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/setting": {
      "filePath": "setting.tsx"
    },
    "/tenant": {
      "filePath": "tenant.tsx",
      "children": [
        "/tenant/master-data/products",
        "/tenant/penjualan/chasier",
        "/tenant/penjualan/sales-invoice",
        "/tenant/user/user-management"
      ]
    },
    "/_unauth/forgotPassword": {
      "filePath": "_unauth/forgotPassword.tsx"
    },
    "/_unauth/landingpage": {
      "filePath": "_unauth/landingpage.tsx"
    },
    "/_unauth/register": {
      "filePath": "_unauth/register.tsx"
    },
    "/_unauth/": {
      "filePath": "_unauth/index.tsx"
    },
    "/tenant/master-data/products": {
      "filePath": "tenant/master-data/products.tsx",
      "parent": "/tenant"
    },
    "/tenant/penjualan/chasier": {
      "filePath": "tenant/penjualan/chasier.tsx",
      "parent": "/tenant"
    },
    "/tenant/penjualan/sales-invoice": {
      "filePath": "tenant/penjualan/sales-invoice.tsx",
      "parent": "/tenant"
    },
    "/tenant/user/user-management": {
      "filePath": "tenant/user/user-management.tsx",
      "parent": "/tenant"
    }
  }
}
ROUTE_MANIFEST_END */
