/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingImport } from './routes/setting'
import { Route as ProfileImport } from './routes/profile'
import { Route as HomepageImport } from './routes/homepage'
import { Route as UnauthIndexImport } from './routes/_unauth/index'
import { Route as UnauthRegisterImport } from './routes/_unauth/register'
import { Route as UnauthForgotPasswordImport } from './routes/_unauth/forgotPassword'

// Create/Update Routes

const SettingRoute = SettingImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const HomepageRoute = HomepageImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => rootRoute,
} as any)

const UnauthIndexRoute = UnauthIndexImport.update({
  id: '/_unauth/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UnauthRegisterRoute = UnauthRegisterImport.update({
  id: '/_unauth/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const UnauthForgotPasswordRoute = UnauthForgotPasswordImport.update({
  id: '/_unauth/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/homepage': {
      id: '/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof HomepageImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingImport
      parentRoute: typeof rootRoute
    }
    '/_unauth/forgotPassword': {
      id: '/_unauth/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof UnauthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_unauth/register': {
      id: '/_unauth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof UnauthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/_unauth/': {
      id: '/_unauth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UnauthIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/homepage': typeof HomepageRoute
  '/profile': typeof ProfileRoute
  '/setting': typeof SettingRoute
  '/forgotPassword': typeof UnauthForgotPasswordRoute
  '/register': typeof UnauthRegisterRoute
  '/': typeof UnauthIndexRoute
}

export interface FileRoutesByTo {
  '/homepage': typeof HomepageRoute
  '/profile': typeof ProfileRoute
  '/setting': typeof SettingRoute
  '/forgotPassword': typeof UnauthForgotPasswordRoute
  '/register': typeof UnauthRegisterRoute
  '/': typeof UnauthIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/homepage': typeof HomepageRoute
  '/profile': typeof ProfileRoute
  '/setting': typeof SettingRoute
  '/_unauth/forgotPassword': typeof UnauthForgotPasswordRoute
  '/_unauth/register': typeof UnauthRegisterRoute
  '/_unauth/': typeof UnauthIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/homepage'
    | '/profile'
    | '/setting'
    | '/forgotPassword'
    | '/register'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/homepage'
    | '/profile'
    | '/setting'
    | '/forgotPassword'
    | '/register'
    | '/'
  id:
    | '__root__'
    | '/homepage'
    | '/profile'
    | '/setting'
    | '/_unauth/forgotPassword'
    | '/_unauth/register'
    | '/_unauth/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomepageRoute: typeof HomepageRoute
  ProfileRoute: typeof ProfileRoute
  SettingRoute: typeof SettingRoute
  UnauthForgotPasswordRoute: typeof UnauthForgotPasswordRoute
  UnauthRegisterRoute: typeof UnauthRegisterRoute
  UnauthIndexRoute: typeof UnauthIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomepageRoute: HomepageRoute,
  ProfileRoute: ProfileRoute,
  SettingRoute: SettingRoute,
  UnauthForgotPasswordRoute: UnauthForgotPasswordRoute,
  UnauthRegisterRoute: UnauthRegisterRoute,
  UnauthIndexRoute: UnauthIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/homepage",
        "/profile",
        "/setting",
        "/_unauth/forgotPassword",
        "/_unauth/register",
        "/_unauth/"
      ]
    },
    "/homepage": {
      "filePath": "homepage.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/setting": {
      "filePath": "setting.tsx"
    },
    "/_unauth/forgotPassword": {
      "filePath": "_unauth/forgotPassword.tsx"
    },
    "/_unauth/register": {
      "filePath": "_unauth/register.tsx"
    },
    "/_unauth/": {
      "filePath": "_unauth/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
